apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ingress-resource-one
spec:
  rules:
  - host: app.terraebb.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: nginx-deploy-main
          servicePort: 80
